stages:
  - build
  - deploy

build prod:
  image: node:10.15.0-stretch
  stage: build
  only:
    - master
  script:
    - npm install
    - npm install -g @vue/cli@latest
    - npm run build
  artifacts:
    paths:
      - dist/
    expire_in: 1 hour
  tags:
    - aha-web-ec2-runner

deploy prod:
  image: python:latest
  stage: deploy
  only:
    - master
  script:
    - pip install awscli
    - aws s3 sync ./dist s3://aha-website-deployment
  tags:
    - aha-web-ec2-runner
