stages:
  - build
  - deploy

build prod:
  image: node:10.15.0-stretch
  stage: build
  only:
    - tags
  script:
    # Install vuecli
    - npm install -g @vue/cli@latest
    # Install dependencies
    - npm install
    # Build App
    - npm run build
  artifacts:
    paths:
      # Build folder
      - dist/
    expire_in: 1 hour
  tags:
    - shared

deploy prod:
  image: python:latest
  stage: deploy
  only:
    - tags
  script:
    - pip install awscli
    - aws s3 sync ./dist s3://aha-website-deployment
  tags:
    - shared

build stage:
  image: node:10.15.0-stretch
  stage: build
  only:
    - dev
  script:
    # Install vuecli
    - npm install -g @vue/cli@latest
    # Install dependencies
    - npm install
    # Build App
    - npm run build-dev
  artifacts:
    paths:
      # Build folder
      - dist/
    expire_in: 1 hour
  tags:
    - shared

deploy stage:
  image: python:latest
  stage: deploy
  only:
    - dev
  script:
    - pip install awscli
    - aws s3 sync ./dist s3://aha-website-deployment
  tags:
    - shared